### ISSUE TITLE
Installation issues while installing ffcv

### ISSUE THREAD

**Issue by mananme02** [RAIVNLab/MRL#22]
After installing the packages present in the requirements file, FFCV module is missing to run the formatting error, when I try to install using the mentioned command in ffcv repo, it gives the following error:

Collecting ffcv
  Using cached ffcv-1.0.2.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ijqwteab/ffcv_59e99b0ddf5845ea8a74d649f62207d9/setup.py", line 96, in <module>
          extension_kwargs = pkgconfig('libturbojpeg', extension_kwargs)
        File "/tmp/pip-install-ijqwteab/ffcv_59e99b0ddf5845ea8a74d649f62207d9/setup.py", line 74, in pkgconfig
          raise RuntimeError(f"Could not find required package: {package}.")
      RuntimeError: Could not find required package: libturbojpeg.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

I tried to install ffcv using the below mentioned command
conda create -y -n ffcv python=3.9 cupy pkg-config libjpeg-turbo opencv pytorch torchvision cudatoolkit=11.3 numba -c pytorch -c conda-forge
conda activate ffcv
pip install ffcv

**Comment by adityakusupati** [comment]
You do not need FFCV unless you want to train on imagenet or use imagenet. FFCV is a package of its own and I am not aware of how to fix this bug. 

@bhattg any clue?

**Comment by yueqirex** [comment]
> You do not need FFCV unless you want to train on imagenet or use imagenet. FFCV is a package of its own and I am not aware of how to fix this bug.
> 
> @bhattg any clue?

However, the only example you showed to train MRL is on imagenet instead of BERT etc., then the following questions persists:
1. What specific FFCV version did you use to train the model?
2. Any chance to specify the package version in the requirements.txt such that users of MRL do not need to try difference versions one by one?
Again appreciate the work but let's work on it together to make it easier to start with and shine in the community. --Thanks.

**Comment by adityakusupati** [comment]
I will wait for @bhattg  for the FFCV version as well.

I think the best way to use MRL in any codebase is to just use the MRL linear layer and loss. So making MRL.py a package is more ideal such that it fits in any pipeline and not rely on a specific training pipeline. 

However, the CLIP style or self-supervised training with MRL doesn't need a linear layer and is only about the loss -- that should be clarified and it is exportable as a simple package.

**Comment by bhattg** [comment]
Hi, @adityakusupati @yueqirex  @mananme02  I haven't encountered this bug before. However,  let me try to see what might be wrong with this newer version of FFCV causing this issue.  Based on those findings, we can modify and/or add remarks to avoid running into this issue. I am assuming you're using the latest FFCV version on their GitHub/pip? 

In terms of the version we had, we used ffcv-v0.0.4 which was the latest at that time (Jan 2022). Hope this helps to get the code running for your task of interest. 

Edit: I am traveling but I should be able to investigate more on this next week. Thanks again for having an interest in our work!

**Comment by mananme02** [comment]
Hi @adityakusupati @bhattg , I was able to resolve the issue by using python 3.11 instead of python 3.9. I feel it is not very clear in the README that how to use MRL with any image classification pipeline. Also, if you could add how to use vision+text models, it would be very helpful.

**Comment by bhattg** [comment]
Hi, @mananme02 happy to know that the issue was resolved after upgrading the Python version. Looks like then it should be something added to the README.md if using the latest version of FFCV. We would update that soon, but to be consistent with our paper, we would specify the version of FFCV we used.  


For the normal classification setting, the best way to use MRL is to add the `MRL.py` package which has the MRL Linear layer, and MRL CE loss, which should work off the shelf by providing an appropriate nesting list in the MRL Linear layer instantiation (along with other flags, if needed).

To answer your question on Vision+Text models, since the loss is applied to the representation space, one doesn't need an MRL Linear Layer. Instead, the only modification is to be done in the loss. For example, in the snippet below, I provide how can one use OpenCLIP's standard CLIP loss, with MRL. 


```python

from torch.nn import functional as F

try:
    import torch.distributed.nn
    from torch import distributed as dist

    has_distributed = True
except ImportError:
    has_distributed = False

try:
    import horovod.torch as hvd
except ImportError:
    hvd = None
from open_clip.loss import gather_features
from open_clip.loss import ClipLoss

class ClipLossMRL(ClipLoss):

    def __init__(
            self,
            nesting_list,
            relative_importance=None,
            local_loss=False,
            gather_with_grad=False,
            cache_labels=False,
            rank=0,
            world_size=1,
            use_horovod=False,
    ):
        super().__init__(local_loss, gather_with_grad, cache_labels, rank, world_size, use_horovod)
        self.nesting_list = nesting_list # [8, 16, 32, 64, 128, 256, 512, 1024, 2048]
        self.relative_importance = [1. for _ in range(len(self.nesting_list))] if relative_importance is None

    def get_logits(self, image_features, text_features, logit_scale, nesting):
        if self.world_size > 1:
            all_image_features, all_text_features = gather_features(
                image_features, text_features,
                self.local_loss, self.gather_with_grad, self.rank, self.world_size, self.use_horovod)

            if self.local_loss:
                logits_per_image = logit_scale * image_features[:, nesting] @ (all_text_features[:, nesting]).T
                logits_per_text = logit_scale * text_features[:, nesting] @ (all_image_features[:, nesting]).T
            else:   
                logits_per_image = logit_scale * all_image_features[:, nesting] @ (all_text_features[:, nesting]).T
                logits_per_text = logits_per_image.T
        else:
            logits_per_image = logit_scale * image_features[:, nesting] @ (text_features[:, nesting]).T
            logits_per_text = logit_scale * text_features[:, nesting] @ (image_features[:, nesting]).T
        
        return logits_per_image, logits_per_text

    def forward(self, image_features, text_features, logit_scale, output_dict=False):
        device = image_features.device
        total_loss  = 0 

        for jj, granularity in enumerate(self.nesting_list):
            logits_per_image, logits_per_text = self.get_logits(image_features, text_features, logit_scale, granularity)
            labels = self.get_ground_truth(device, logits_per_image.shape[0])
            total_loss += self.relative_importance[jj]*(F.cross_entropy(logits_per_image, labels) + F.cross_entropy(logits_per_text, labels)) / 2

        return {"contrastive_loss": total_loss} if output_dict else total_loss
```

The code above uses OpenCLIP's implementation and therefore you'd see the distributed gathering operation commands,  but overall, the main change is when one is computing `logits_per_image` or `logits_per_text` where we chose the first `nesting` dimensions to provide the granularity. 

Thus, in similar ways one can make changes to other Loss functions (which only use representations), by providing - `nesting_list` and `relative_importance` (if None, every granularity is weighed equally). 


We will provide a pseudocode in the README.md reflecting this change.  Hope this helps!

**Comment by mananme02** [comment]
Thank You for providing such detailed explanation. It would be great help and hoping to use this soon in a project.
